### ISSUE TITLE
config.yaml的风格需要统一

### ISSUE THREAD

**Issue by sljeff** [shanbay/gobay#8]
在sentry_mw里的做法是在server.go里面直接把sub viper传进去

```golang
// config.yaml
defaults: &defaults
  db_driver: sqlite3
  db_url: ':memory:'
  grpc_conn_timeout: 5s
development:
  <<: *defaults
  sentry:
    dsn: 'https://xxx:xxx@sentry.xxxx.com/00'

// app/openapi/server.go
sentry_middleware, _ := sentry_mw.GetOpenAPIMiddleware(app.Config().Sub("sentry"))
```

---

esapmext里的做法是

```golang
serverUrl, err := url.Parse(config.GetString("elastic_apm_server_url"))
```

**Comment by sljeff** [comment]
我觉得应该用sub viper的写法，更好使用，viper.Sub(NS)就可以取到一个子配置，ext不用自己去拼字符串。

这样的话yaml写法应该如下（NS为sentry）：

```yaml
sentry: &sentry
  dsn: 'http://user:pass@127.0.0.1/5'
  environment: 'default'

# 自定义配置
defaults: defaults
  project_name: 'gobay'
  sentry:
    <<: *sentry
staging:
  <<: *defaults
  sentry:
    <<: *sentry
```

然后为了可以从环境变量读到，ext.go里需要增加两句：
```golang
        if d.NS != "" {
                config = config.Sub(d.NS)
                config.SetEnvPrefix(d.NS)  // 1
        }
        config.AutomaticEnv()  // 2
```

然后NS是sentry，想要覆盖sentry下面的dsn配置，只需要添加一个环境变量`SENTRY_DSN`。
